### ISSUE TITLE
Doesn't seem to support IE11

### ISSUE THREAD

**Issue by shaohua** [Versal/component-runtime#5]
No error message, just blank.

The custom element is not upgraded.
![screen shot 2014-06-04 at 4 37 18 pm](https://cloud.githubusercontent.com/assets/806173/3181581/38a123fe-ec41-11e3-92b5-e578873e40e8.png)

If replaced with the platform.js, then it seems to work.
![screen shot 2014-06-04 at 4 38 18 pm](https://cloud.githubusercontent.com/assets/806173/3181592/579bc642-ec41-11e3-944c-913aa41244a4.png)

Might need to add additional polyfills from platform.js for IE11

**Comment by janpaul123** [comment]
Fixed in #6
